### ISSUE TITLE
Task 3: Coloured Table

### ISSUE THREAD

**Issue by PradyumnaKrishna** [CC-BHU/web-development#17]
Simple and easy task, won't take more than a day.

**Task**
Write HTML to generate the following output.
![Table](https://user-images.githubusercontent.com/51270439/233893482-10431516-85ab-4922-b94d-2fb8532a0387.png)

**Style Guide**
- [ ] Table must be in centre of the HTML page and have appropriate border.
- [ ] `min-width` must be `75px` for table cells.
- [ ] Colour the table cells accordingly.
- [ ] Text must be centered in cells.

**Comment by PradyumnaKrishna** [comment]
Solution: https://github.com/CC-BHU/web-development/blob/main/solutions/task3.html
