### ISSUE TITLE
Task 4: Navbar

### ISSUE THREAD

**Issue by PradyumnaKrishna** [CC-BHU/web-development#24]
This task would be little bit challenging as I am not providing much info.

**Task**
Write a HTML that creates
- [ ] A `navbar` with 3 buttons.
- [ ] 3 Sections with full vertical height and `text-center`.
- [ ] Button should link to the sections, i.e. on pressing the button the section would scroll up.
- [ ] Sections can be anything, i.e. Home, About, Action etc.

**Style Guide**
To help you style the navbar, a css file is provided. You can link it to your HTML using `<link>` in the header. The href is `/assets/css/navbar.css`.

**NOTE: First sync your fork with CC-BHU to get the css file.**

**Demo**
![Demo](https://user-images.githubusercontent.com/51270439/234745738-adb7adba-9b45-4ade-9927-d7b8e3f8bae7.gif)

**NOTE: no javascript is required.**

**Comment by PradyumnaKrishna** [comment]
Solution: https://github.com/CC-BHU/web-development/blob/main/solutions/task4.html
