### ISSUE TITLE
Task 5: Form

### ISSUE THREAD

**Issue by PradyumnaKrishna** [CC-BHU/web-development#30]
**Task**
Create a html page `task5.html` that contains a registration form with:
- [ ] An input field for name
- [ ] A input for date of birth with calender
- [ ] A radio input for Gender `male`, `female` and `other`
- [ ] A checkbox for selection of tech stacks (`AI`, `ML`, `Cloud`, `Web`, `Mobile`, `DevOps`, and `System`)
- [ ] An input field for email
- [ ] An input field for phone no
- [ ] A selector to select a security question with following options
  - What is your favourite book?
  - What is your nickname?
  - What is your birth town?
  - Other
 - [ ] A textbox to answer the question
 - [ ] A file upload input for resume
 - [ ] Submit and Reset button

**Comment by PradyumnaKrishna** [comment]
Solution: https://github.com/CC-BHU/web-development/blob/main/solutions/task5.html
