### ISSUE TITLE
Task 7: Dropdown Navbar

### ISSUE THREAD

**Issue by PradyumnaKrishna** [CC-BHU/web-development#48]
This time the navbar is back but with dropdowns.

**Task**
Create a `task7.html` that contain a navbar having two items.
- [ ] First item should be `Hover` that enables dropdown on hover.
- [ ] Second item should be `Click` that enables dropdown on click.
- [ ] Both dropdown contains three items `Profile`, `Coding Club` and `Repository` linking to successive locations.

**Style Guide**
- [ ] Navbar should be light in color
- [ ] Make the navbar rounded at corners
- [ ] Navbar items should change color
- [ ] Dropdown should be rounded at corners as well
- [ ] Add hover properties to dropdown items to make responsive
- [ ] Add good shadow to the dropdown elements

**Demo**
![Demo](https://github.com/CC-BHU/web-development/assets/51270439/ec203b35-56ad-449b-b820-33049bf23067)

**Comment by PradyumnaKrishna** [comment]
Solution: https://github.com/CC-BHU/web-development/blob/main/solutions/task7.html
