### ISSUE TITLE
Task 8: Modal

### ISSUE THREAD

**Issue by PradyumnaKrishna** [CC-BHU/web-development#63]
**Task**
Create a html file `task8.html` that
- [ ] Have the [image]() in the centre of page.
- [ ] On clicking the image a modal should appear on the top.
- [ ] Modal will header, body and footer.
  - Modal header should contain `Red Dahlia Flower`.
  - Add suitable paragraph in the modal body.
  - Footer should contain two button `Close` and `Download` that performs the suitable functionality.

**Style Guide**
- [ ] Image should have a width of 50% and should be horizontally and vertically centered.
- [ ] On hover over image an image border should appear (try to add transition).
- [ ] Modal should have appropriate shadows.
- [ ] Modal buttons should be right aligned.

**Demo**
![Demo](https://github.com/CC-BHU/web-development/assets/51270439/97910206-a44b-4b42-94a7-779f799f746c)

**Comment by PradyumnaKrishna** [comment]
Solution: https://github.com/CC-BHU/web-development/blob/main/solutions/task8.html
