### ISSUE TITLE
Task 2: Retro City

### ISSUE THREAD

**Issue by PradyumnaKrishna** [CC-BHU/web-development#8]
Congratulations of completing the Task 1. The difficulty is increased for this task. Search on your own and try to build the webpage as shown in the image below.

**Task**
A image is present in `assets` having path `assets/images/task2.jpg` and url <https://github.com/CC-BHU/web-development/raw/main/assets/images/task2.jpg>

- [ ] Create a webpage `task2.html` with title `Retro City`.
- [ ] Add a image provided with full width, i.e. 100%.
- [ ] Create a text box on bottom right of the image.
- [ ] Put some text inside box, for example: `Welcome to the Retro city, feel like a game?`
- [ ] Add shadow to the text box `10px 10px` with some color other than `black`.

**Hint**
Put the image and text inside a `div` with position relative.

**Demo**
![Screenshot](https://user-images.githubusercontent.com/51270439/232856216-b0f581e6-cced-4d6b-b678-54171cedc7de.png)

**Comment by PradyumnaKrishna** [comment]
Solution: https://github.com/CC-BHU/web-development/blob/main/solutions/task2.html
