### ISSUE TITLE
Task 10: Form Validation and JSON

### ISSUE THREAD

**Issue by PradyumnaKrishna** [CC-BHU/web-development#90]
**Task**
Create a HTML `task10.html`, that contains a form with:
- [ ] A selection that takes a function `linear`, `inverse` and `log`.
- [ ] A input that takes a number.
- [ ] A submit button.

**Mark both input as required.**

Use JavaScript to perform following operations
- [ ] If `inverse` is selected and 0 is given in input, alert with "wrong input".
- [ ] If `log` is selected and non positive no is given in input, alert with "wrong input".
- [ ] Calculate the result of the functions `x`, `1/x` and `log(x)` for `linear`, `inverse` and `log` functions respectively and show the result on web page.
- [ ] Also convert the form data into JSON, append the `result` and show the json on web page (Use `<pre>` tag for code block). 

**Screenshots**
<img width="278" alt="Screenshot 2023-05-24 at 11 31 18" src="https://github.com/CC-BHU/web-development/assets/51270439/19ad6173-e998-4313-94c6-cb3dfb643b1a">
<img width="472" alt="Screenshot 2023-05-24 at 11 31 38" src="https://github.com/CC-BHU/web-development/assets/51270439/25c0dd4f-d98c-49c2-89c3-efa7fe17dd94">

**Reference**
Convert form data to json: https://stackabuse.com/convert-form-data-to-javascript-object

**Comment by PradyumnaKrishna** [comment]
Solution: https://github.com/CC-BHU/web-development/blob/main/solutions/task10.html
